# -*- coding: utf-8 -*-
"""Siamese_Network_Setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XtFNY4PoXYMjY2fhFxi2WYWhFoUNNZN
"""

import cv2
import os
import random
import numpy as np
import uuid
from matplotlib import pyplot as plt
import tensorflow as tf
from datasets import load_dataset
from tqdm import tqdm

# Limit GPU memory growth
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

# Set up paths
POS_PATH = os.path.join('data', 'positive')
NEG_PATH = os.path.join('data', 'negative')
ANC_PATH = os.path.join('data', 'anchor')

os.makedirs(POS_PATH, exist_ok=True)
os.makedirs(NEG_PATH, exist_ok=True)
os.makedirs(ANC_PATH, exist_ok=True)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Conv2D, Dense, MaxPooling2D, Input, Flatten

from google.colab import drive
drive.mount('/content/drive')

!unzip -q /content/drive/MyDrive/Face_Recognition/data.zip -d /content/

POS_PATH = '/content/data/positive'
NEG_PATH = '/content/data/negative'
ANC_PATH = '/content/data/anchor'

# Establish connection to webcam (0 for built-in, 1 for external)
cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()

    # Cut down frame to 250px X 250px
    frame = frame[120:120+250, 200:200+250, :]

    # Show image back to screen
    cv2.imshow('Image Collection', frame)

    # Catch the key press exactly ONCE per frame
    key = cv2.waitKey(1) & 0xFF

    # Collect anchors
    if key == ord('a'):
        imgname = os.path.join(ANC_PATH, '{}.jpg'.format(uuid.uuid1()))
        cv2.imwrite(imgname, frame)
        print(f"Saved Anchor: {imgname}")

    # Collect positives
    elif key == ord('p'):
        imgname = os.path.join(POS_PATH, '{}.jpg'.format(uuid.uuid1()))
        cv2.imwrite(imgname, frame)
        print(f"Saved Positive: {imgname}")

    # Breaking gracefully
    elif key == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

anchor = tf.data.Dataset.list_files(os.path.join(ANC_PATH, '*.jpg')).take(300)
positive = tf.data.Dataset.list_files(os.path.join(POS_PATH, '*.jpg')).take(300)
negative = tf.data.Dataset.list_files(os.path.join(NEG_PATH, '*.jpg')).take(300)

dir_test =anchor.as_numpy_iterator()
dir_test.next()

# 1. Function to process a SINGLE image
def preprocess(file_path):
    byte_img = tf.io.read_file(file_path)
    img = tf.io.decode_jpeg(byte_img)

    # Resize the image down to exactly 100x100
    img = tf.image.resize(img, (100, 100))
    # Scale image pixels between 0 and 1
    img = img / 255.0
    return img

# 2. Function to process the TWIN images and label together
def preprocess_twin(input_img, validation_img, label):
    return (preprocess(input_img), preprocess(validation_img), label)

img = preprocess('/content/data/anchor/d5a5dc2f-2655-11f1-b074-ebcd63ce1246.jpg')

"""Creating the Labeled Dataset
# (anchor , pos) => 1,1,1,1
# (anchor , neg) => 0,0,0,0
"""

positives = tf.data.Dataset.zip((anchor, positive, tf.data.Dataset.from_tensor_slices((tf.ones(len(anchor))))))
negatives = tf.data.Dataset.zip((anchor, negative, tf.data.Dataset.from_tensor_slices((tf.zeros(len(anchor))))))

# Look here! Changed positive to positives
data = positives.concatenate(negatives)

samples = data.as_numpy_iterator()
samples.next()

data =data.map(preprocess_twin)
data = data.cache()
data = data.shuffle(buffer_size=1024)



data

"""train | test partition"""

train_data = data.take(round(len(data)*.7))
train_data = train_data.batch(16)
train_data = train_data.prefetch(8)

train_samples =train_data.as_numpy_iterator()
train_samples = train_samples.next()
len(train_samples[0])

# testing partition
test_data = data.skip(round(len(data)*.7))
test_data = data.take(round(len(data)*.3))
test_data = train_data.batch(16)
test_data = train_data.prefetch(8)

"""Model eng | building embedding layer"""

from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Dense, Flatten,Layer
from tensorflow.keras.models import Model

inp = Input(shape=(100,100,3), name='input_image')
c1 = Conv2D(64, (10,10), activation='relu')(inp)
m1 = MaxPooling2D(64, (2,2), padding='same')(c1)
c2 = Conv2D(128, (7,7), activation='relu')(m1)
m2 = MaxPooling2D(64, (2,2), padding='same')(c2)
c3 = Conv2D(128, (4,4), activation='relu')(m2)
m3 = MaxPooling2D(64, (2,2), padding='same')(c3)
c4 = Conv2D(256, (4,4), activation='relu')(m3)
f1 = Flatten()(c4)
d1 = Dense(4096, activation='sigmoid')(f1)

mod = Model(inputs=[inp], outputs=[d1], name='embedding')

mod.summary()

def make_embedding():
    inp = Input(shape=(100,100,3) , name = 'input_image')

    #first block
    c1 = Conv2D(64,(10,10) , activation ='relu')(inp)
    m1 = MaxPooling2D(64, (2,2) , padding = 'same')(c1)

    #second block
    c2 =Conv2D(128 ,(7,7) , activation ='relu')(m1)
    m2 = MaxPooling2D(64, (2,2) , padding = 'same')(c2)

    #third block
    c3 =Conv2D(128 ,(4,4) , activation ='relu')(m2)
    m3 = MaxPooling2D(64, (2,2), padding='same')(c3)

    #final embedding block
    c4 = Conv2D(256, (4,4), activation='relu')(m3)
    f1 = Flatten()(c4)
    d1 = Dense(4096, activation='sigmoid')(f1)

    return Model(inputs=[inp], outputs=[d1], name='embedding')

embedding = make_embedding()
embedding.summary()

"""BUilding distance Layer"""

class L1Dist(Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, input_embedding, validation_embedding):
        # Check if Keras wrapped the output in a list, and extract the tensor if so
        if isinstance(input_embedding, list):
            input_embedding = input_embedding[0]
        if isinstance(validation_embedding, list):
            validation_embedding = validation_embedding[0]

        # Now we can safely calculate the absolute difference
        return tf.math.abs(input_embedding - validation_embedding)

l1 = L1Dist()
import tensorflow as tf

# 1. Instantiate your custom distance layer (if you haven't already in this cell)
l1 = L1Dist()

# 2. Create some fake "dummy" embeddings to test the layer (Shape: 1 batch, 4096 features)
anchor_embedding = tf.random.normal([1, 4096])
validation_embedding = tf.random.normal([1, 4096])

# 3. Pass them through your distance layer
distance_result = l1(anchor_embedding, validation_embedding)

# 4. Print the result!
print("Distance Calculation Shape:", distance_result.shape)
print("Distance Values:", distance_result)

l1(anchor_embedding, validation_embedding)

"""Make sieme Model"""

input_image = Input(name='input_img', shape=(100,100,3))
validation_image = Input(name='validation_img', shape=(100,100,3))

inp_embedding = embedding(input_image)
val_embedding = embedding(validation_image)
siamese_layer = L1Dist()
distances = siamese_layer(inp_embedding, val_embedding)

classifier = Dense(1, activation='sigmoid')(distances)
classifier

siamese_network = Model(inputs=[input_image, validation_image], outputs=classifier, name='SiameseNetwork')

siamese_network.summary()

def make_siamese_model():

    #Anchor image input in network
    input_image = Input(name='input_img',shape =(100,100,3))

    #validation image in the network
    validation_image = Input(name='validation_image',shape =(100,100,3))

    #combine siamese distance component
    siamese_layer =L1Dist()
    siamese_layer.name ='distance'
    distances = siamese_layer(embedding(input_image), embedding(validation_image))

    # Classification layer
    classifier = Dense(1, activation='sigmoid')(distances)

    return Model(inputs=[input_image, validation_image], outputs=classifier, name='SiameseNetwork')

siamese_model = make_siamese_model()

siamese_model.summary()

"""5. training

5.1 stepip loss and optimizer
"""

binary_cross_loss = tf.losses.BinaryCrossentropy()

# 1. First, define the optimizer (Adam is the standard choice with a learning rate of 1e-4)
opt = tf.keras.optimizers.Adam(learning_rate=1e-4)

# 2. Then, pass it into the checkpoint along with your model
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt')
checkpoint = tf.train.Checkpoint(opt=opt, siamese_model=siamese_model)

"""Build train step function"""

test_batch = train_data.as_numpy_iterator()
batch_1 = test_batch.next()

X = batch_1[:2]

y = batch_1[2]
y

@tf.function
def train_step(batch):

    # Record all of our operations
    with tf.GradientTape() as tape:
        # Get anchor and positive/negative image
        X = batch[:2]
        # Get label
        y = batch[2]

        # Forward pass
        yhat = siamese_model(X, training=True)
        # Calculate loss
        loss = binary_cross_loss(y, yhat)
    print(loss)

    # Calculate gradients
    grad = tape.gradient(loss, siamese_model.trainable_variables)

    # Calculate updated weights and apply to siamese model
    opt.apply_gradients(zip(grad, siamese_model.trainable_variables))

    # Return loss
    return loss

# Import metric calculations
from tensorflow.keras.metrics import Precision, Recall

def train(data, EPOCHS):
    # Loop through epochs
    for epoch in range(1, EPOCHS+1):
        print('\n Epoch {}/{}'.format(epoch, EPOCHS))
        progbar = tf.keras.utils.Progbar(len(data))

        # Creating a metric object
        r = Recall()
        p = Precision()

        # Loop through each batch
        for idx, batch in enumerate(data):
            # Run train step here
            loss = train_step(batch)
            yhat = siamese_model.predict(batch[:2])
            r.update_state(batch[2], yhat)
            p.update_state(batch[2], yhat)
            progbar.update(idx+1)
        print(loss.numpy(), r.result().numpy(), p.result().numpy())

        # Save checkpoints
        if epoch % 10 == 0:
            checkpoint.save(file_prefix=checkpoint_prefix)

"""Train the mode"""

EPOCHS = 50

# Change this:
# checkpoint_dir = './training_checkpoints'

# To an absolute path outside of OneDrive:
checkpoint_dir = r'C:\Temp\FaceRecog_Checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt')
checkpoint = tf.train.Checkpoint(opt=opt, siamese_model=siamese_model)

train(train_data, EPOCHS)

"""Evaluate the Model"""

# Import metric calculations
from tensorflow.keras.metrics import Precision, Recall

# Get a batch of test data
test_input, test_val, y_true = test_data.as_numpy_iterator().next()

y_hat = siamese_model.predict([test_input, test_val])

[1 if prediction > 0.5 else 0 for prediction in y_hat ]

y_true

"""Calculate Metrics"""

# Creating a metric object
m = Recall()

# Calculating the recall value
m.update_state(y_true, y_hat)

# Return Recall Result
m.result().numpy()

# Creating a metric object
m = Precision()

# Calculating the recall value
m.update_state(y_true, y_hat)

# Return Recall Result
m.result().numpy()

r = Recall()
p = Precision()

for test_input, test_val, y_true in test_data.as_numpy_iterator():
    yhat = siamese_model.predict([test_input, test_val])
    r.update_state(y_true, yhat)
    p.update_state(y_true,yhat)

print(r.result().numpy(), p.result().numpy())

# Set plot size
plt.figure(figsize=(10,8))

# Set first subplot
plt.subplot(1,2,1)
plt.imshow(test_input[0])

# Set second subplot
plt.subplot(1,2,2)
plt.imshow(test_val[0])

# Renders cleanly
plt.show()

# Save weights
siamese_model.save('siamesemodelv3.h5')

L1Dist

# Reload model
siamese_model = tf.keras.models.load_model('siamesemodelv3.h5',
                                   custom_objects={'L1Dist':L1Dist, 'BinaryCrossentropy':tf.losses.BinaryCrossentropy})

# Make predictions with reloaded model
siamese_model.predict([test_input, test_val])

# View model summary
siamese_model.summary()

"""8. Real Time Test

8.1 Verification Function
"""

import shutil

# Define paths for application data
APP_DATA_PATH = 'application_data'
INPUT_IMAGE_PATH = os.path.join(APP_DATA_PATH, 'input_image')
VERIFICATION_IMAGES_PATH = os.path.join(APP_DATA_PATH, 'verification_images')

# Create directories if they don't exist
os.makedirs(INPUT_IMAGE_PATH, exist_ok=True)
os.makedirs(VERIFICATION_IMAGES_PATH, exist_ok=True)

# Populate with placeholder images (using existing anchor images)
# For input_image
anchor_files = os.listdir(ANC_PATH)
if anchor_files:
    # Copy the first anchor image to input_image
    shutil.copy(os.path.join(ANC_PATH, anchor_files[0]), os.path.join(INPUT_IMAGE_PATH, 'input_image.jpg'))
    print(f"Copied {anchor_files[0]} to {INPUT_IMAGE_PATH}/input_image.jpg")
else:
    print("No anchor images found to populate input_image.")

# For verification_images (copy a few anchor images)
for i, filename in enumerate(anchor_files):
    if i < 5: # Copy up to 5 images for verification
        shutil.copy(os.path.join(ANC_PATH, filename), os.path.join(VERIFICATION_IMAGES_PATH, filename))
        print(f"Copied {filename} to {VERIFICATION_IMAGES_PATH}/{filename}")
    else:
        break

os.listdir(VERIFICATION_IMAGES_PATH)
print(os.path.join(INPUT_IMAGE_PATH, 'input_image.jpg'))
for image in os.listdir(VERIFICATION_IMAGES_PATH):
    validation_img = os.path.join(VERIFICATION_IMAGES_PATH, image)
    print(validation_img)

def verify(model, detection_threshold, verification_threshold):
    # Build results array
    results = []
    for image in os.listdir(os.path.join('application_data', 'verification_images')):
        input_img = preprocess(os.path.join('application_data', 'input_image', 'input_image.jpg'))
        validation_img = preprocess(os.path.join('application_data', 'verification_images', image))

        # Make Predictions
        result = model.predict(list(np.expand_dims([input_img, validation_img], axis=1)))
        results.append(result)

    # Detection Threshold: Metric above which a prediciton is considered positive
    detection = np.sum(np.array(results) > detection_threshold)

    # Verification Threshold: Proportion of positive predictions / total positive samples
    verification = detection / len(os.listdir(os.path.join('application_data', 'verification_images')))
    verified = verification > verification_threshold

    return results, verified

"""8.2 OpenCV Real Time Verification"""

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import numpy as np
import os

# 1. Ensure the directories exist
os.makedirs(os.path.join('application_data', 'input_image'), exist_ok=True)

# 2. Define the Javascript Web-Cam Capture Function
def take_photo_and_verify(filename='application_data/input_image/input_image.jpg', quality=0.8):
    js = Javascript('''
    async function takePhoto(quality) {
        const div = document.createElement('div');
        const capture = document.createElement('button');
        capture.textContent = 'Capture for Verification';
        capture.style.padding = '10px 20px';
        capture.style.fontSize = '16px';
        capture.style.backgroundColor = '#4CAF50';
        capture.style.color = 'white';
        div.appendChild(capture);

        const video = document.createElement('video');
        video.style.display = 'block';
        const stream = await navigator.mediaDevices.getUserMedia({video: true});

        document.body.appendChild(div);
        div.appendChild(video);
        video.srcObject = stream;
        await video.play();

        // Resize the output to fit the video element
        google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

        // Wait for Capture button to be clicked
        await new Promise((resolve) => capture.onclick = resolve);

        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);
        stream.getVideoTracks()[0].stop();
        div.remove();
        return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])

    # 3. Convert Javascript image back to OpenCV format
    image_arr = np.frombuffer(binary, dtype=np.uint8)
    frame = cv2.imdecode(image_arr, cv2.IMREAD_COLOR)

    # 4. Apply your exact crop (handling potential browser resolution differences)
    try:
        frame = frame[120:120+250, 200:200+250, :]
    except Exception as e:
        print("Warning: Browser camera resolution differed. Resizing instead.")
        frame = cv2.resize(frame, (250, 250))

    # 5. Save the image to the application_data folder
    cv2.imwrite(filename, frame)
    print(f"Image saved to {filename}")

    return filename

# --- RUN THE VERIFICATION LOOP ---
try:
    print("Starting webcam... Click the green 'Capture' button when ready.")

    # Take the photo
    take_photo_and_verify()

    # Run the verification function
    results, verified = verify(siamese_model, 0.5, 0.5)

    print("-" * 30)
    print("VERIFICATION RESULT:", verified)
    print("RAW SCORES:", results)
    print("-" * 30)

except Exception as err:
    # Errors will be thrown if the user cancels the webcam permission
    print(str(err))

np.sum(np.squeeze(results) > 0.9)

results





